version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: vxtwitter_prod
    command: npm start
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    environment:
      - NODE_ENV=prod
    env_file:
      - .env
